version: "3"
services:
    mind-map-dev:
        build:
            context: .
            dockerfile: Dockerfile
        image: rcldsl/mind-map-dev 
        working_dir: /home/node/working
        environment: 
            - NODE_ENV=development
        volumes:
            - ./:/home/node/working
        ports:
            - 3000:3000