version: "3"
services:
    mind-map-dev:
        build:
            context: .
            dockerfile: Dockerfile
        image: rcldsl/mind-map-dev 
        working_dir: /home/node/working
        environment: 
            - NODE_ENV=development
        volumes:
            - ./:/home/node/working
            - /home/node/working/node_modules
        ports:
            - ${MIND_MAP_PORT}:3000
        restart: always